input               regSData_awvalid,
output              M01_AXI_0_awready,
input      [19:0]   M01_AXI_0_awaddr,
input      [2:0]    M01_AXI_0_awprot,
input               M01_AXI_0_wvalid,
output              M01_AXI_0_wready,
input      [31:0]   M01_AXI_0_wdata,
input      [3:0]    M01_AXI_0_wstrb,
output              M01_AXI_0_bvalid,
input               M01_AXI_0_bready,
output     [1:0]    M01_AXI_0_bresp,
input               M01_AXI_0_arvalid,
output              M01_AXI_0_arready,
input      [19:0]   M01_AXI_0_araddr,
input      [2:0]    M01_AXI_0_arprot,
output              M01_AXI_0_rvalid,
input               M01_AXI_0_rready,
output     [31:0]   M01_AXI_0_rdata,
output     [1:0]    M01_AXI_0_rresp,
input               clk,
input      [63:0]   s_axis_s2mm_tdata,
input      [7:0]    s_axis_s2mm_tkeep,
input               s_axis_s2mm_tlast,
output              s_axis_s2mm_tready,
input               s_axis_s2mm_tvalid,
output     [63:0]   m_axis_mm2s_tdata,
output     [7:0]    m_axis_mm2s_tkeep,
output              m_axis_mm2s_tlast,
input               m_axis_mm2s_tready,
output              m_axis_mm2s_tvalid,
input               reset