function [] = ReadWrite_DMA(TxAddr,TxLength,RxAddr,RxLength)
    assert((string(class(RxAddr))=="string")&&(string(class(TxAddr))=="string"));
        fprintf("Status = XAxiDma_SimpleTransfer(&AxiDma,(UINTPTR)(%s),%d, XAXIDMA_DEVICE_TO_DMA);\n" + ...
        "if (Status != XST_SUCCESS) {//启动DMA接收\n" + ...
        "return XST_FAILURE;\n" + ...
        "}\n" + ...
        "Status = XAxiDma_SimpleTransfer(&AxiDma,(UINTPTR)(%s),%d, XAXIDMA_DMA_TO_DEVICE);\n" + ...
        "if (Status != XST_SUCCESS) {//启动dMA发送\n" + ...
        "return XST_FAILURE;\n" + ...
        "}\n" + ...
        "while ((!TxDone||!RxDone) && !Error) {" + ...
        "}\n" + ...
        "TxDone=0;RxDone=0;\n",RxAddr,RxLength,TxAddr,TxLength);

end