function []= Write_DMA(SendLength)
    fprintf("Status = XAxiDma_SimpleTransfer(&AxiDma,(UINTPTR)WEIGHT_BASE_ADDR,%d, XAXIDMA_DMA_TO_DEVICE);\n" + ...
        "if (Status != XST_SUCCESS) {//启动dMA发送\n" + ...
        "return XST_FAILURE;\n" + ...
        "}\n" + ...
        "while ((!TxDone || !RxDone) && !Error) {" + ...
        "}\n",SendLength);
end