function [] = Read_DMA(ReadLength,varargin)
    if(size(varargin,2)==0)
        fprintf("Status = XAxiDma_SimpleTransfer(&AxiDma,(UINTPTR)CONV_RESULT_BASE_ADDR,%d, XAXIDMA_DEVICE_TO_DMA);\n" + ...
        "if (Status != XST_SUCCESS) {//启动DMA接收\n" + ...
        "return XST_FAILURE;\n" + ...
        "}\n" + ...
        "while ((!RxDone) && !Error) {" + ...
        "}\n",ReadLength);
    else
        assert(string(class(varargin{1}))=="string");
        fprintf("Status = XAxiDma_SimpleTransfer(&AxiDma,(UINTPTR)(%s),%d, XAXIDMA_DEVICE_TO_DMA);\n" + ...
        "if (Status != XST_SUCCESS) {//启动DMA接收\n" + ...
        "return XST_FAILURE;\n" + ...
        "}\n" + ...
        "while ((!RxDone) && !Error) {" + ...
        "}\n",varargin{1},ReadLength);
    end
end