function []= Write_DMA(SendLength,varargin)
    if(size(varargin,2)==1)
        assert(string(class(varargin{1}))=="string");
        fprintf("Status = XAxiDma_SimpleTransfer(&AxiDma,(UINTPTR)(%s),%d, XAXIDMA_DMA_TO_DEVICE);\n" + ...
        "if (Status != XST_SUCCESS) {//启动dMA发送\n" + ...
        "return XST_FAILURE;\n" + ...
        "}\n" + ...
        "while ((!TxDone) && !Error) {" + ...
        "}\n" + ...
        "TxDone=0;\n",varargin{1},SendLength);
    else
    fprintf("Status = XAxiDma_SimpleTransfer(&AxiDma,(UINTPTR)WEIGHT_BASE_ADDR,%d, XAXIDMA_DMA_TO_DEVICE);\n" + ...
        "if (Status != XST_SUCCESS) {//启动dMA发送\n" + ...
        "return XST_FAILURE;\n" + ...
        "}\n" + ...
        "while ((!TxDone) && !Error) {" + ...
        "}\n" + ...
        "TxDone=0;\n",SendLength);
    end
end